export const countries = [
  {
    name: 'Messico',
    battleground: true,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: 'USA',
    region: 'CA',
  },
  {
    name: 'Guatemala',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'CA',
  },
  {
    name: 'Cuba',
    battleground: true,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: 'USA',
    region: 'CA',
  },
  {
    name: 'Haiti',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'CA',
  },
  {
    name: 'Rep. Dominicana',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'CA',
  },
  {
    name: 'El Salvador',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'CA',
  },
  {
    name: 'Honduras',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'CA',
  },
  {
    name: 'Nicaragua',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: 'USA',
    region: 'CA',
  },
  {
    name: 'Costa Rica',
    battleground: false,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'CA',
  },
  {
    name: 'Panama',
    battleground: true,
    stability: 2,
    blueInfluence: 1,
    redInfluence: 0,
    adjacentTo: null,
    region: 'CA',
  },
  {
    name: 'Venezuela',
    battleground: true,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'SA',
  },
  {
    name: 'Brasile',
    battleground: true,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'SA',
  },
  {
    name: 'Cile',
    battleground: true,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'SA',
  },
  {
    name: 'Colombia',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'SA',
  },
  {
    name: 'Ecuador',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'SA',
  },
  {
    name: 'Perù',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'SA',
  },
  {
    name: 'Bolivia',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'SA',
  },
  {
    name: 'Paraguay',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'SA',
  },
  {
    name: 'Uruguay',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'SA',
  },
  {
    name: 'Argentina',
    battleground: true,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'SA',
  },
  {
    name: 'Algeria',
    battleground: true,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Nigeria',
    battleground: true,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Zaire',
    battleground: true,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Angola',
    battleground: true,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Sud Africa',
    battleground: true,
    stability: 3,
    blueInfluence: 1,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Marocco',
    battleground: false,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Tunisia',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Stati Africani Occiden.',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Stati del Sahara',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Sudan',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Etiopia',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Somalia',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: "Costa d'Avorio",
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Camerun',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Kenya',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Stati Africani del SE',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Zimbabwe',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Botswana',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Africa',
  },
  {
    name: 'Libano',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'ME',
  },
  {
    name: 'Siria',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 1,
    adjacentTo: null,
    region: 'ME',
  },
  {
    name: 'Giordania',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'ME',
  },
  {
    name: 'Stati del Golfo',
    battleground: false,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'ME',
  },
  {
    name: 'Israele',
    battleground: true,
    stability: 4,
    blueInfluence: 1,
    redInfluence: 0,
    adjacentTo: null,
    region: 'ME',
  },
  {
    name: 'Iraq',
    battleground: true,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 1,
    adjacentTo: null,
    region: 'ME',
  },
  {
    name: 'Iran',
    battleground: true,
    stability: 2,
    blueInfluence: 1,
    redInfluence: 0,
    adjacentTo: null,
    region: 'ME',
  },
  {
    name: 'Libia',
    battleground: true,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'ME',
  },
  {
    name: 'Egitto',
    battleground: true,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'ME',
  },
  {
    name: 'Arabia Saudita',
    battleground: true,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'ME',
  },
  {
    name: 'Canada',
    battleground: false,
    stability: 4,
    blueInfluence: 2,
    redInfluence: 0,
    adjacentTo: 'USA',
    region: 'Europe',
  },
  {
    name: 'Finlandia',
    battleground: false,
    stability: 4,
    blueInfluence: 0,
    redInfluence: 1,
    adjacentTo: 'URSS',
    region: 'Europe',
  },
  {
    name: 'Romania',
    battleground: false,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: 'URSS',
    region: 'Europe',
  },
  {
    name: 'Polonia',
    battleground: true,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: 'URSS',
    region: 'Europe',
  },
  {
    name: 'Italy',
    battleground: true,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Germania Est',
    battleground: true,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 3,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Germania Ovest',
    battleground: true,
    stability: 4,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Francia',
    battleground: true,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Norvegia',
    battleground: false,
    stability: 4,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Svezia',
    battleground: false,
    stability: 4,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Danimarca',
    battleground: false,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Regno Unito',
    battleground: false,
    stability: 5,
    blueInfluence: 5,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Benelux',
    battleground: false,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Cecoslovacchia',
    battleground: false,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Austria',
    battleground: false,
    stability: 4,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Ungheria',
    battleground: false,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Spagna/Portogallo',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Jugoslavia',
    battleground: false,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Bulgaria',
    battleground: false,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Turchia',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Grecia',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Europe',
  },
  {
    name: 'Afghanistan',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: 'URSS',
    region: 'Asia',
  },
  {
    name: 'Corea del Nord',
    battleground: true,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 3,
    adjacentTo: 'URSS',
    region: 'Asia',
  },
  {
    name: 'Giappone',
    battleground: true,
    stability: 4,
    blueInfluence: 1,
    redInfluence: 0,
    adjacentTo: 'USA',
    region: 'Asia',
  },
  {
    name: 'Pakistan',
    battleground: true,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Asia',
  },
  {
    name: 'India',
    battleground: true,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Asia',
  },
  {
    name: 'Thailandia',
    battleground: true,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Asia',
    subregion: 'SEAsia',
  },
  {
    name: 'Corea del Sud',
    battleground: true,
    stability: 3,
    blueInfluence: 1,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Asia',
  },
  {
    name: 'Birmania',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Asia',
    subregion: 'SEAsia',
  },
  {
    name: 'Laos/Cambogia',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Asia',
    subregion: 'SEAsia',
  },
  {
    name: 'Taiwan',
    battleground: false,
    stability: 3,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    tempBattleground: false,
    region: 'Asia',
  },
  {
    name: 'Vietnam',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Asia',
    subregion: 'SEAsia',
  },
  {
    name: 'Filippine',
    battleground: false,
    stability: 2,
    blueInfluence: 1,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Asia',
    subregion: 'SEAsia',
  },
  {
    name: 'Malesia',
    battleground: false,
    stability: 2,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Asia',
    subregion: 'SEAsia',
  },
  {
    name: 'Indonesia',
    battleground: false,
    stability: 1,
    blueInfluence: 0,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Asia',
    subregion: 'SEAsia',
  },
  {
    name: 'Australia',
    battleground: false,
    stability: 4,
    blueInfluence: 4,
    redInfluence: 0,
    adjacentTo: null,
    region: 'Asia',
    subregion: 'SEAsia',
  },
];
